[package]
name = "libri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
xml-rs = "0.8.4"
zip = "0.5.13"
